### PR TITLE
Feature reg form validation

### PR DESCRIPTION
**Pull request by tnathu-ai**

### CODE REVIEW

**Comment by miketvo** [comment]
I have assumed responsibility for completing this branch. Please wait for me to finish it.

**Review by miketvo — DISMISSED** [review]

**Review by rider3458 — APPROVED** [review]
Dear @TriDang, 

By approving these changes, I agree that @tnathu-ai will assume full responsibility for any bug(s) that may arise related to, or because of, her object-oriented code in line 44 - 270 within `public/js/account/register.js`.

In such case, if she fails to debug the above mentioned code before the deadline of May 8th 2021, she will receive a 5% deduction penalty to her final grade, in addition to any grade drop for the whole group due to said bug(s).

Otherwise, her grade will remain equal to the others' in the group.

This is because @tnathu-ai used object-oriented programming (OOP) approach for the above-mentioned code, whilst not having a full understanding of OOP. All members of our group, including @tnathu-ai, have agreed that it is fair for @tnathu-ai to take this risk to get our approval for this pull request (#35).

**Review by doanyennhi — APPROVED** [review]
Dear @TriDang, 

By approving these changes, I agree that @tnathu-ai will assume full responsibility for any bug(s) that may arise related to, or because of, her object-oriented code in line 44 - 270 within `public/js/account/register.js`.

In such case, if she fails to debug the above mentioned code before the deadline of May 8th 2021, she will receive a 5% deduction penalty to her final grade, in addition to any grade drop for the whole group due to said bug(s).

Otherwise, her grade will remain equal to the others' in the group.

This is because @tnathu-ai used object-oriented programming (OOP) approach for the above-mentioned code, whilst not having a full understanding of OOP. All members of our group, including @tnathu-ai, have agreed that it is fair for @tnathu-ai to take this risk to get our approval for this pull request (#35).

**Comment by TriDang** [comment]
Hi all

I noted your comments/reviews. BTW, I suggest that the team manage the contributions of members yourselves. You only need to send me the final contribution information when submitting the work on Canvas.

But keeping all reviews like this is good, in case there are disputes among members later.

Best

**Comment by miketvo** [comment]
Dear @TriDang 

Thank you for your reply.

Yes, we enforced these reviews for this pull request (#35) in case of disputes among members later, we can use this as proof of our agreement. This also serves as a deterrent against uncooperative/egotistical behaviors in future pull requests, prompted by recent incidents in our group related to team member @tnathu-ai that resulted in delays in our overall progress. We had discussed among ourselves, and agreed that this is a fair response to said incidents.

We sincerely hope that we won't have to resort to this method again in the future.

Thank you again for your time.

**Pull request merged**
