### PR TITLE
Feature add to cart

### PR DESCRIPTION
**Pull request by rider3458**
add empty message when the cart is empty
add product's info to local storage with key = "cartProducts"
delete sample html div in cart
add line for listing products from cart-display.js

### CODE REVIEW

**Review by miketvo — DISMISSED** [review]
Please add functionality to the "+" and "-" buttons in `public/mall/cart/index.html

**Review by doanyennhi — DISMISSED** [review]
- Add more comments in functions
- On cart page, when clicking on the image of product detail 2, it redirects to 1st product-detail page

**Review by tnathu-ai — COMMENTED** [review]
missing flashing message to let users know that their chosen product has just been added

**Review by miketvo — CHANGES_REQUESTED** [review]
Please add functionality for the "Remove" button in the cart page.

Also, please fix the link issue mentioned by @doanyennhi in [this change request](https://github.com/kuri-team/yabe-online-mall/pull/34#pullrequestreview-647331179)

**Comment by rider3458** [comment]
For the issue that the 2nd product has the wrong product link, please try to clear the localStorage and try again.
I have tested on 2 devices and haven't met the mentioned issue.
Please inform me whenever the issue is solved or not.
Thank you.

**Review by miketvo — APPROVED** [review]

**Review by doanyennhi — CHANGES_REQUESTED** [review]
- Message flashes too quickly
- Should restyle the message. It's too small

**Review by miketvo — CHANGES_REQUESTED** [review]
Product price not updating when increasing product quantitu

**Review by doanyennhi — APPROVED** [review]

**Pull request merged**
